// Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: module/item/itemPb/itemPb.proto

package hello_microservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structures
type FindItemsInIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindItemsInIdsReq) Reset() {
	*x = FindItemsInIdsReq{}
	mi := &file_module_item_itemPb_itemPb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindItemsInIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindItemsInIdsReq) ProtoMessage() {}

func (x *FindItemsInIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_module_item_itemPb_itemPb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindItemsInIdsReq.ProtoReflect.Descriptor instead.
func (*FindItemsInIdsReq) Descriptor() ([]byte, []int) {
	return file_module_item_itemPb_itemPb_proto_rawDescGZIP(), []int{0}
}

func (x *FindItemsInIdsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindItemsInIdsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindItemsInIdsRes) Reset() {
	*x = FindItemsInIdsRes{}
	mi := &file_module_item_itemPb_itemPb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindItemsInIdsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindItemsInIdsRes) ProtoMessage() {}

func (x *FindItemsInIdsRes) ProtoReflect() protoreflect.Message {
	mi := &file_module_item_itemPb_itemPb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindItemsInIdsRes.ProtoReflect.Descriptor instead.
func (*FindItemsInIdsRes) Descriptor() ([]byte, []int) {
	return file_module_item_itemPb_itemPb_proto_rawDescGZIP(), []int{1}
}

func (x *FindItemsInIdsRes) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Damage        int32                  `protobuf:"varint,5,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_module_item_itemPb_itemPb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_module_item_itemPb_itemPb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_module_item_itemPb_itemPb_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Item) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

var File_module_item_itemPb_itemPb_proto protoreflect.FileDescriptor

const file_module_item_itemPb_itemPb_proto_rawDesc = "" +
	"\n" +
	"\x1fmodule/item/itemPb/itemPb.proto\"%\n" +
	"\x11FindItemsInIdsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"0\n" +
	"\x11FindItemsInIdsRes\x12\x1b\n" +
	"\x05items\x18\x01 \x03(\v2\x05.ItemR\x05items\"v\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bimageUrl\x18\x04 \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06damage\x18\x05 \x01(\x05R\x06damage2K\n" +
	"\x0fItemGrpcService\x128\n" +
	"\x0eFindItemsInIds\x12\x12.FindItemsInIdsReq\x1a\x12.FindItemsInIdsResB)Z'github.com/bunkai888/hello-microserviceb\x06proto3"

var (
	file_module_item_itemPb_itemPb_proto_rawDescOnce sync.Once
	file_module_item_itemPb_itemPb_proto_rawDescData []byte
)

func file_module_item_itemPb_itemPb_proto_rawDescGZIP() []byte {
	file_module_item_itemPb_itemPb_proto_rawDescOnce.Do(func() {
		file_module_item_itemPb_itemPb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_item_itemPb_itemPb_proto_rawDesc), len(file_module_item_itemPb_itemPb_proto_rawDesc)))
	})
	return file_module_item_itemPb_itemPb_proto_rawDescData
}

var file_module_item_itemPb_itemPb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_module_item_itemPb_itemPb_proto_goTypes = []any{
	(*FindItemsInIdsReq)(nil), // 0: FindItemsInIdsReq
	(*FindItemsInIdsRes)(nil), // 1: FindItemsInIdsRes
	(*Item)(nil),              // 2: Item
}
var file_module_item_itemPb_itemPb_proto_depIdxs = []int32{
	2, // 0: FindItemsInIdsRes.items:type_name -> Item
	0, // 1: ItemGrpcService.FindItemsInIds:input_type -> FindItemsInIdsReq
	1, // 2: ItemGrpcService.FindItemsInIds:output_type -> FindItemsInIdsRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_module_item_itemPb_itemPb_proto_init() }
func file_module_item_itemPb_itemPb_proto_init() {
	if File_module_item_itemPb_itemPb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_item_itemPb_itemPb_proto_rawDesc), len(file_module_item_itemPb_itemPb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_item_itemPb_itemPb_proto_goTypes,
		DependencyIndexes: file_module_item_itemPb_itemPb_proto_depIdxs,
		MessageInfos:      file_module_item_itemPb_itemPb_proto_msgTypes,
	}.Build()
	File_module_item_itemPb_itemPb_proto = out.File
	file_module_item_itemPb_itemPb_proto_goTypes = nil
	file_module_item_itemPb_itemPb_proto_depIdxs = nil
}
